spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1/mindmotion?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
#    password: 123456
#    url: jdbc:mysql://192.168.235.129/mindmotion?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /generalpack